# Generated by Django 3.1.5 on 2021-07-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=100)),
                ('s1', models.BooleanField(default=False)),
                ('s2', models.BooleanField(default=False)),
                ('s3', models.BooleanField(default=False)),
                ('s4', models.BooleanField(default=False)),
                ('s5', models.BooleanField(default=False)),
                ('s6', models.BooleanField(default=False)),
                ('s7', models.BooleanField(default=False)),
                ('s8', models.BooleanField(default=False)),
                ('s9', models.BooleanField(default=False)),
                ('s10', models.BooleanField(default=False)),
                ('sr', models.BooleanField(default=False)),
                ('jr', models.BooleanField(default=False)),
            ],
        ),
    ]
