# Generated by Django 3.1.5 on 2021-07-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachingStaff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='english',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='hindi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='marathi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='maths',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='science',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='socialScience',
            field=models.BooleanField(default=False),
        ),
    ]
