# Generated by Django 3.1.5 on 2021-07-01 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachingStaff', '0002_auto_20210701_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='jr',
            new_name='jtd_sr',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='s1',
            new_name='std_1',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='s10',
            new_name='std_10',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='s2',
            new_name='std_2',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='s3',
            new_name='std_3',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='s4',
            new_name='std_4',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='s5',
            new_name='std_5',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='s6',
            new_name='std_6',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='s7',
            new_name='std_7',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='s8',
            new_name='std_8',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='s9',
            new_name='std_9',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='sr',
            new_name='std_jr',
        ),
    ]
