# Generated by Django 3.1.5 on 2021-07-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachingStaff', '0005_auto_20210701_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='stdjr',
            new_name='stdJr',
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='teacher', max_length=50),
        ),
    ]
