# Generated by Django 3.1.5 on 2021-07-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachingStaff', '0006_auto_20210702_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='t_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
