# Generated by Django 3.1.5 on 2021-06-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_rollNo', models.CharField(max_length=10)),
                ('s_name', models.CharField(max_length=50)),
                ('s_father', models.CharField(max_length=50)),
                ('s_surname', models.CharField(max_length=50)),
                ('s_mother', models.CharField(max_length=50)),
                ('s_phone', models.CharField(max_length=10)),
                ('s_standard', models.CharField(max_length=20)),
                ('s_age', models.IntegerField()),
                ('s_birth', models.DateField()),
                ('s_address', models.CharField(max_length=500)),
                ('s_gender', models.CharField(max_length=20)),
            ],
        ),
    ]
