# Generated by Django 3.1.5 on 2021-06-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='s_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
