# Generated by Django 3.1.5 on 2021-06-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_s_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='s_password',
            field=models.CharField(default='admin', max_length=50),
        ),
    ]
