# Generated by Django 3.1.5 on 2021-07-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20210630_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='class10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng', models.CharField(max_length=254)),
                ('mat', models.CharField(max_length=254)),
                ('sci', models.CharField(max_length=254)),
                ('sosci', models.CharField(max_length=254)),
                ('hin', models.CharField(max_length=254)),
                ('mar', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='class6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng', models.CharField(max_length=254)),
                ('mat', models.CharField(max_length=254)),
                ('sci', models.CharField(max_length=254)),
                ('sosci', models.CharField(max_length=254)),
                ('hin', models.CharField(max_length=254)),
                ('mar', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='class7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng', models.CharField(max_length=254)),
                ('mat', models.CharField(max_length=254)),
                ('sci', models.CharField(max_length=254)),
                ('sosci', models.CharField(max_length=254)),
                ('hin', models.CharField(max_length=254)),
                ('mar', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='class8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng', models.CharField(max_length=254)),
                ('mat', models.CharField(max_length=254)),
                ('sci', models.CharField(max_length=254)),
                ('sosci', models.CharField(max_length=254)),
                ('hin', models.CharField(max_length=254)),
                ('mar', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='class9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng', models.CharField(max_length=254)),
                ('mat', models.CharField(max_length=254)),
                ('sci', models.CharField(max_length=254)),
                ('sosci', models.CharField(max_length=254)),
                ('hin', models.CharField(max_length=254)),
                ('mar', models.CharField(max_length=254)),
            ],
        ),
    ]
