# Generated by Django 3.1.5 on 2021-07-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_class10_class6_class7_class8_class9'),
    ]

    operations = [
        migrations.AddField(
            model_name='class10',
            name='engf',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='class10',
            name='hinf',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='class10',
            name='marf',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='class10',
            name='matf',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='class10',
            name='scif',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='class10',
            name='soscif',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='class6',
            name='engf',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='class6',
            name='hinf',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='class6',
            name='marf',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='class6',
            name='matf',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='class6',
            name='scif',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='class6',
            name='soscif',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='class7',
            name='engf',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='class7',
            name='hinf',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='class7',
            name='marf',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='class7',
            name='matf',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='class7',
            name='scif',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='class7',
            name='soscif',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='class8',
            name='engf',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='class8',
            name='hinf',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='class8',
            name='marf',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='class8',
            name='matf',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='class8',
            name='scif',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='class8',
            name='soscif',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='class9',
            name='engf',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='class9',
            name='hinf',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='class9',
            name='marf',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='class9',
            name='matf',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='class9',
            name='scif',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='class9',
            name='soscif',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
