# Generated by Django 3.1.5 on 2021-07-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20210702_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class10',
            name='eng',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='class10',
            name='hin',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='class10',
            name='mar',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='class10',
            name='mat',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='class10',
            name='sci',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='class10',
            name='sosci',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='class6',
            name='eng',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='class6',
            name='hin',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='class6',
            name='mar',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='class6',
            name='mat',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='class6',
            name='sci',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='class6',
            name='sosci',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='class7',
            name='eng',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='class7',
            name='hin',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='class7',
            name='mar',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='class7',
            name='mat',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='class7',
            name='sci',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='class7',
            name='sosci',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='class8',
            name='eng',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='class8',
            name='hin',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='class8',
            name='mar',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='class8',
            name='mat',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='class8',
            name='sci',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='class8',
            name='sosci',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='class9',
            name='eng',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='class9',
            name='hin',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='class9',
            name='mar',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='class9',
            name='mat',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='class9',
            name='sci',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='class9',
            name='sosci',
            field=models.CharField(default='', max_length=254),
        ),
    ]
